version: '3'
services:
  emby:
    image: emby/embyserver
    container_name: emby
    restart: unless-stopped
    volumes:
      - "$STACK_DATA/config:/config"
      - "$MEDIA_LOCATION:/media"
    environment:
      - UID=$PUID
      - GID=$PGID
      - GIDLIST=$PGID,44
    devices:
      - /dev/dri:/dev/dri
    networks:
      - "webapp"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.emby.rule=Host(`emby.${DOMAIN}`)"
      - "traefik.http.routers.emby.entrypoints=websecure"
      - "traefik.http.routers.emby.tls.certresolver=leresolver"
      - traefik.http.services.emby.loadbalancer.server.port=8096
      - "traefik.http.middlewares.embyHeaders.headers.contentSecurityPolicy=default-src 'self' https:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' https:; img-src 'self' https:"
      - "traefik.http.middlewares.embyHeaders.headers.framedeny=true"
      - "traefik.http.middlewares.embyHeaders.headers.sslredirect=true"
      - "traefik.http.middlewares.embyHeaders.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.embyHeaders.headers.stsPreload=true"
      - "traefik.http.middlewares.embyHeaders.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.embyHeaders.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.embyHeaders.headers.browserXssFilter=true"
      - "traefik.http.middlewares.embyHeaders.headers.stsSeconds=31536000"
      - "traefik.http.routers.emby.middlewares=embyHeaders"
networks:
  webapp:
    external:
      name: 'webapp'